spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wishlist
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update