spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wishlist?serverTimezone=Europe/Minsk&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    username: root
    password: springroot
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update